backend:
  name: github
  repo: TyphaineLeGales/jean-danielou
  branch: update-multilanguage-structure
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

i18n:
  structure: multiple_folders
  locales: [fr, en]
  default_locale: fr

collections:
  - name: "landing"
    label: "Landing"
    folder: "src/content/landing"
    create: false
    i18n: true
    fields:
      - { label: "Catch phrase", name: "catch", widget: "string", i18n: true }
      - { label: "Text", name: "text", widget: "markdown", i18n: true }

  - name: "books"
    label: "Books"
    folder: "src/content/books"
    create: true
    i18n: true
    fields:
      - { label: "ID", name: "id", widget: "number", required: true, i18n: duplicate }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Year", name: "date", widget: "string", i18n: duplicate }
      - { label: "Featured Image", name: "thumbnail", widget: "image", i18n: duplicate }
      - { label: "Catch phrase", name: "lead", widget: "text", i18n: true }
      - { label: "Excerpt", name: "body", widget: "markdown", i18n: true }
      - label: "Reviews"
        name: "reviews"
        widget: "list"
        # i18n: true - use the same one from fr
        fields:
          - { label: "Link", name: "link", widget: "string" }
          - { label: "Date", name: "date", widget: "string", required: false }
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Author", name: "author", widget: "string", required: false }
          - { label: "Published in", name: "published", widget: "string", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        # i18n: true - use the same one from fr
        fields:
          - { label: "Image", name: "image", widget: "image"}
          - { label: "Description", name: "alt", widget: "string" }

  - name: "medias"
    label: "Medias"
    folder: "src/content/medias"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Date", name: "date", widget: "string", i18n: duplicate }
      - { label: "Link", name: "link", widget: "string", i18n: duplicate }
      - { label: "Published on", name: "publishedon", widget: "string", i18n: duplicate }
      - { label: "Description", name: "text", widget: "string", i18n: true }

  - name: "academic"
    label: "Academic"
    folder: "src/content/academic"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Date", name: "date", widget: "string", i18n: duplicate }
      - { label: "Link", name: "link", widget: "string", i18n: duplicate }
      - { label: "Published on", name: "publishedon", widget: "string", i18n: duplicate }
      - { label: "Description", name: "text", widget: "string", i18n: true }
      - label: "Tags"
        name: "tags"
        widget: "list"
        i18n: true
        fields:
          - { label: "Name", name: "name", widget: "string" }

  - name: "collaborations"
    label: "Collaborations"
    folder: "src/content/collaborations"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - label: "Collaborators"
        name: "collaborators"
        widget: "list"
        i18n: true
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Role", name: "role", widget: "string", i18n: true}
          - { label: "Link", name: "link", widget: "string", i18n: true}
      - { label: "Time status", name: "time", widget: "string", i18n: duplicate }
      - { label: "Lead", name: "lead", widget: text, i18n: true}
      - { label: "Description", name: "body", widget: "markdown", i18n: true }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", i18n: duplicate }
      - { label: "Thumbnail alt", name: "thumbnailalt", widget: "string", i18n: true }
      - { label: "PDF", name: "pdf", widget: "file", required: false, i18n: duplicate }
      - label: "Images"
        name: "images"
        widget: "list"
        i18n: true
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "alt", widget: "string" }

  - name: "selected works"
    label: "selected works"
    folder: "src/content/selected"
    create: true
    i18n: true
    fields: 
    - { label: "Title", name: "title", widget: "string", i18n: true}
    - {label: "link", name: "link", widget: "string", i18n: duplicate}
    - {label: "Type - book, collab etc...", name: "type", i18n: true}
    - {label: "Date", name: "date", widget: "string", i18n: duplicate}