backend:
  name: github
  repo: TyphaineLeGales/jean-danielou
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "landing_en"
    label: "landing EN"
    folder: "src/content/landing/en"
    create: false
    fields: 
      - {label: "Catch phrase", name: "catch", widget: "string"}
      - { label: "Text", name: "text", widget: "markdown"}
  - name: "landing_fr"
    label: "landing FR"
    folder: "src/content/landing/fr"
    create: false
    fields: 
      - {label: "Phrase d'accroche", name: "catch", widget: "string"}
      - { label: "Text", name: "text", widget: "markdown"}
  - name: "books_en"
    label: "Books EN"
    folder: "src/content/books/en"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Year", name: "date", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Catch phrase", name: "lead", widget: "text" }
      - { label: "Excerpt", name: "body", widget: "markdown" }
      - label: "Reviews"
        name: "reviews"
        widget: "list"
        fields:
          - { label: "Review Text", name: "text", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
          - { label: "Date", name: "date", widget: "string", required: false}
          - { label: "Title", name: "title", widget: "string", required: false}
          - { label: "Author", name: "author", widget: "string",required: false}
          - { label: "Published in", name: "published", widget: "string", required: false}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "image", name: "image", widget: "image"}
          - { label: "description", name: "alt", widget: "string"}
  - name: "books_fr"
    label: "Books FR"
    folder: "src/content/books/fr"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Année de publication", name: "date", widget: "string" }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - {label: "Phrase d'accroche", name: "lead", widget: "text" }
      - { label: "Extrait", name: "body", widget: "markdown" }
      - label: "Recensions"
        name: "reviews"
        widget: "list"
        fields:
          - { label: "Infos", name: "text", widget: "string" }
          - { label: "Lien", name: "link", widget: "string" }
          - { label: "Date", name: "date", widget: "string", required: false}
          - { label: "Titre", name: "title", widget: "string", required: false}
          - { label: "Autheur", name: "author", widget: "string", required: false}
          - { label: "Publiée sur", name: "published", widget: "string", required: false}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "image", name: "image", widget: "image"}
          - { label: "description", name: "alt", widget: "string"}
  - name: "medias_fr"
    label: "Medias FR"
    folder: "src/content/medias/fr"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Lien", name: "link", widget: "string" }
      - { label: "Publié sur", name: "publishedon", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
  - name: "medias_en"
    label: "Medias EN"
    folder: "src/content/medias/en"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Published on", name: "publishedon", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
  - name: "academic_fr"
    label: "Academic FR"
    folder: "src/content/academic/fr"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Lien", name: "link", widget: "string" }
      - { label: "Publié sur", name: "publishedon", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - { label: "Name", name: "text", widget: "string" }
  - name: "academic_en"
    label: "Academic EN"
    folder: "src/content/academic/en"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Published on", name: "publishedon", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
  - name: "collaborations_fr"
    label: "Collaborations FR"
    folder: "src/content/collaborations/fr"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: string}
      - label: collaborateurices
        name: "collaborators"
        widget: "list"
        fields: 
          - {label: "Nom", name: "name", widget: "string"}
      - { label: "Time status", name: "time", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown"}
      - { label: "Thumbnail", name: "thumbnail", widget: "image"}
      - { label: "Thumbnail alt", name: "thumbnailalt", widget: "string"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "image", name: "image", widget: "image"}
          - { label: "description", name: "alt", widget: "string"}
  - name: "collaborations_en"
    label: "Collaborations EN"
    folder: "src/content/collaborations/en"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: string}
      - label: collaborators
        name: "collaborators"
        widget: "list"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
      - { label: "Time status", name: "time", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown"}
      - { label: "Thumbnail", name: "thumbnail", widget: "image"}
      - { label: "Thumbnail alt", name: "thumbnailalt", widget: "string"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "image", name: "image", widget: "image"}
          - { label: "description", name: "alt", widget: "string"}
  
