backend:
  name: github
  repo: TyphaineLeGales/jean-danielou
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "books_en"
    label: "Books EN"
    folder: "src/content/books/en"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Year", name: "date", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Catch phrase", name: "lead", widget: "text" }
      - { label: "Excerpt", name: "body", widget: "markdown" }
      - label: "Reviews"
        name: "reviews"
        widget: "list"
        fields:
          - { label: "Review Text", name: "text", widget: "string" }
          - { label: "Review Link", name: "link", widget: "string" }
  - name: "books_fr"
    label: "Books FR"
    folder: "src/content/books/fr"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Année de publication", name: "date", widget: "string" }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - {label: "Phrase d'accroche", name: "lead", widget: "text" }
      - { label: "Extrait", name: "body", widget: "markdown" }
      - label: "Recensions"
        name: "reviews"
        widget: "list"
        fields:
          - { label: "Infos", name: "text", widget: "string" }
          - { label: "Lien", name: "link", widget: "string" }