name: Build and Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Enable pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get pnpm store path
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build Astro site
        run: pnpm build

      - name: Remove admin from production build
        run: rm -rf dist/admin
      
      - name: Test SSH connection
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -y -f ~/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -i ~/.ssh/id_ed25519 \
            ${{ secrets.SSH_NAME }}@${{ secrets.SSH_HOST }} echo "SSH works!"

     
      - name: Deploy to Infomaniak via Rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          path: ./dist/
          remote_path: /sites/jeandanielou.com/
          remote_host:  ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_NAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: 22